# -*- coding: utf-8 -*-

# Copyright 2021 Tianmian Tech. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scheduler.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='scheduler.proto',
  package='visualfl',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0fscheduler.proto\x12\x08visualfl\"i\n\x04Init\x1a\x13\n\x03REQ\x12\x0c\n\x04name\x18\x01 \x01(\t\x1a,\n\x03REP\x12%\n\x06status\x18\x01 \x01(\x0e\x32\x15.visualfl.Init.Status\"\x1e\n\x06Status\x12\n\n\x06REJECT\x10\x00\x12\x08\n\x04INIT\x10\x01\"\x97\x01\n\nWorkerJoin\x1a!\n\x03REQ\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04step\x18\x02 \x01(\r\x1a\x32\n\x03REP\x12+\n\x06status\x18\x01 \x01(\x0e\x32\x1b.visualfl.WorkerJoin.Status\"2\n\x06Status\x12\n\n\x06REJECT\x10\x00\x12\x10\n\x0cNOT_SELECTED\x10\x01\x12\n\n\x06\x41\x43\x43\x45PT\x10\x02\"y\n\x0cWorkerFinish\x1a\x13\n\x03REQ\x12\x0c\n\x04name\x18\x01 \x01(\t\x1a\x34\n\x03REP\x12-\n\x06status\x18\x01 \x01(\x0e\x32\x1d.visualfl.WorkerFinish.Status\"\x1e\n\x06Status\x12\n\n\x06REJECT\x10\x00\x12\x08\n\x04\x44ONE\x10\x01\x32\xcb\x01\n\tScheduler\x12\x30\n\x04Init\x12\x12.visualfl.Init.REQ\x1a\x12.visualfl.Init.REP\"\x00\x12\x42\n\nWorkerJoin\x12\x18.visualfl.WorkerJoin.REQ\x1a\x18.visualfl.WorkerJoin.REP\"\x00\x12H\n\x0cWorkerFinish\x12\x1a.visualfl.WorkerFinish.REQ\x1a\x1a.visualfl.WorkerFinish.REP\"\x00\x62\x06proto3'
)



_INIT_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='visualfl.Init.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REJECT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INIT', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=104,
  serialized_end=134,
)
_sym_db.RegisterEnumDescriptor(_INIT_STATUS)

_WORKERJOIN_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='visualfl.WorkerJoin.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REJECT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOT_SELECTED', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACCEPT', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=238,
  serialized_end=288,
)
_sym_db.RegisterEnumDescriptor(_WORKERJOIN_STATUS)

_WORKERFINISH_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='visualfl.WorkerFinish.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REJECT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DONE', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=381,
  serialized_end=411,
)
_sym_db.RegisterEnumDescriptor(_WORKERFINISH_STATUS)


_INIT_REQ = _descriptor.Descriptor(
  name='REQ',
  full_name='visualfl.Init.REQ',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='visualfl.Init.REQ.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=56,
)

_INIT_REP = _descriptor.Descriptor(
  name='REP',
  full_name='visualfl.Init.REP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='visualfl.Init.REP.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=102,
)

_INIT = _descriptor.Descriptor(
  name='Init',
  full_name='visualfl.Init',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_INIT_REQ, _INIT_REP, ],
  enum_types=[
    _INIT_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=134,
)


_WORKERJOIN_REQ = _descriptor.Descriptor(
  name='REQ',
  full_name='visualfl.WorkerJoin.REQ',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='visualfl.WorkerJoin.REQ.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='step', full_name='visualfl.WorkerJoin.REQ.step', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=184,
)

_WORKERJOIN_REP = _descriptor.Descriptor(
  name='REP',
  full_name='visualfl.WorkerJoin.REP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='visualfl.WorkerJoin.REP.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=236,
)

_WORKERJOIN = _descriptor.Descriptor(
  name='WorkerJoin',
  full_name='visualfl.WorkerJoin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_WORKERJOIN_REQ, _WORKERJOIN_REP, ],
  enum_types=[
    _WORKERJOIN_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=288,
)


_WORKERFINISH_REQ = _descriptor.Descriptor(
  name='REQ',
  full_name='visualfl.WorkerFinish.REQ',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='visualfl.WorkerFinish.REQ.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=56,
)

_WORKERFINISH_REP = _descriptor.Descriptor(
  name='REP',
  full_name='visualfl.WorkerFinish.REP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='visualfl.WorkerFinish.REP.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=327,
  serialized_end=379,
)

_WORKERFINISH = _descriptor.Descriptor(
  name='WorkerFinish',
  full_name='visualfl.WorkerFinish',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_WORKERFINISH_REQ, _WORKERFINISH_REP, ],
  enum_types=[
    _WORKERFINISH_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=290,
  serialized_end=411,
)

_INIT_REQ.containing_type = _INIT
_INIT_REP.fields_by_name['status'].enum_type = _INIT_STATUS
_INIT_REP.containing_type = _INIT
_INIT_STATUS.containing_type = _INIT
_WORKERJOIN_REQ.containing_type = _WORKERJOIN
_WORKERJOIN_REP.fields_by_name['status'].enum_type = _WORKERJOIN_STATUS
_WORKERJOIN_REP.containing_type = _WORKERJOIN
_WORKERJOIN_STATUS.containing_type = _WORKERJOIN
_WORKERFINISH_REQ.containing_type = _WORKERFINISH
_WORKERFINISH_REP.fields_by_name['status'].enum_type = _WORKERFINISH_STATUS
_WORKERFINISH_REP.containing_type = _WORKERFINISH
_WORKERFINISH_STATUS.containing_type = _WORKERFINISH
DESCRIPTOR.message_types_by_name['Init'] = _INIT
DESCRIPTOR.message_types_by_name['WorkerJoin'] = _WORKERJOIN
DESCRIPTOR.message_types_by_name['WorkerFinish'] = _WORKERFINISH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Init = _reflection.GeneratedProtocolMessageType('Init', (_message.Message,), {

  'REQ' : _reflection.GeneratedProtocolMessageType('REQ', (_message.Message,), {
    'DESCRIPTOR' : _INIT_REQ,
    '__module__' : 'scheduler_pb2'
    # @@protoc_insertion_point(class_scope:visualfl.Init.REQ)
    })
  ,

  'REP' : _reflection.GeneratedProtocolMessageType('REP', (_message.Message,), {
    'DESCRIPTOR' : _INIT_REP,
    '__module__' : 'scheduler_pb2'
    # @@protoc_insertion_point(class_scope:visualfl.Init.REP)
    })
  ,
  'DESCRIPTOR' : _INIT,
  '__module__' : 'scheduler_pb2'
  # @@protoc_insertion_point(class_scope:visualfl.Init)
  })
_sym_db.RegisterMessage(Init)
_sym_db.RegisterMessage(Init.REQ)
_sym_db.RegisterMessage(Init.REP)

WorkerJoin = _reflection.GeneratedProtocolMessageType('WorkerJoin', (_message.Message,), {

  'REQ' : _reflection.GeneratedProtocolMessageType('REQ', (_message.Message,), {
    'DESCRIPTOR' : _WORKERJOIN_REQ,
    '__module__' : 'scheduler_pb2'
    # @@protoc_insertion_point(class_scope:visualfl.WorkerJoin.REQ)
    })
  ,

  'REP' : _reflection.GeneratedProtocolMessageType('REP', (_message.Message,), {
    'DESCRIPTOR' : _WORKERJOIN_REP,
    '__module__' : 'scheduler_pb2'
    # @@protoc_insertion_point(class_scope:visualfl.WorkerJoin.REP)
    })
  ,
  'DESCRIPTOR' : _WORKERJOIN,
  '__module__' : 'scheduler_pb2'
  # @@protoc_insertion_point(class_scope:visualfl.WorkerJoin)
  })
_sym_db.RegisterMessage(WorkerJoin)
_sym_db.RegisterMessage(WorkerJoin.REQ)
_sym_db.RegisterMessage(WorkerJoin.REP)

WorkerFinish = _reflection.GeneratedProtocolMessageType('WorkerFinish', (_message.Message,), {

  'REQ' : _reflection.GeneratedProtocolMessageType('REQ', (_message.Message,), {
    'DESCRIPTOR' : _WORKERFINISH_REQ,
    '__module__' : 'scheduler_pb2'
    # @@protoc_insertion_point(class_scope:visualfl.WorkerFinish.REQ)
    })
  ,

  'REP' : _reflection.GeneratedProtocolMessageType('REP', (_message.Message,), {
    'DESCRIPTOR' : _WORKERFINISH_REP,
    '__module__' : 'scheduler_pb2'
    # @@protoc_insertion_point(class_scope:visualfl.WorkerFinish.REP)
    })
  ,
  'DESCRIPTOR' : _WORKERFINISH,
  '__module__' : 'scheduler_pb2'
  # @@protoc_insertion_point(class_scope:visualfl.WorkerFinish)
  })
_sym_db.RegisterMessage(WorkerFinish)
_sym_db.RegisterMessage(WorkerFinish.REQ)
_sym_db.RegisterMessage(WorkerFinish.REP)



_SCHEDULER = _descriptor.ServiceDescriptor(
  name='Scheduler',
  full_name='visualfl.Scheduler',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=414,
  serialized_end=617,
  methods=[
  _descriptor.MethodDescriptor(
    name='Init',
    full_name='visualfl.Scheduler.Init',
    index=0,
    containing_service=None,
    input_type=_INIT_REQ,
    output_type=_INIT_REP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='WorkerJoin',
    full_name='visualfl.Scheduler.WorkerJoin',
    index=1,
    containing_service=None,
    input_type=_WORKERJOIN_REQ,
    output_type=_WORKERJOIN_REP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='WorkerFinish',
    full_name='visualfl.Scheduler.WorkerFinish',
    index=2,
    containing_service=None,
    input_type=_WORKERFINISH_REQ,
    output_type=_WORKERFINISH_REP,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SCHEDULER)

DESCRIPTOR.services_by_name['Scheduler'] = _SCHEDULER

# @@protoc_insertion_point(module_scope)
