
###
POST http://localhost:8080/board-service/union/data_resource/detail
Content-Type: application/json
token:{{token}}

{
  "data_resource_id": "c2c38a92d494451e87bf0c61db6a8aa6",
  "data_resource_type": "TableDataSet"
}

