# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: basic-meta.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='basic-meta.proto',
    package='com.welab.wefe.gateway.api.meta.basic',
    syntax='proto3',
    serialized_options=b'B\016BasicMetaProto',
    serialized_pb=b'\n\x10\x62\x61sic-meta.proto\x12%com.welab.wefe.gateway.api.meta.basic\"6\n\x08\x45ndpoint\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x10\n\x08hostname\x18\x03 \x01(\t\"O\n\tEndpoints\x12\x42\n\tendpoints\x18\x01 \x03(\x0b\x32/.com.welab.wefe.gateway.api.meta.basic.Endpoint\"N\n\x0cReturnStatus\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\tsessionId\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\tB\x10\x42\x0e\x42\x61sicMetaProtob\x06proto3'
)

_ENDPOINT = _descriptor.Descriptor(
    name='Endpoint',
    full_name='com.welab.wefe.gateway.api.meta.basic.Endpoint',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='ip', full_name='com.welab.wefe.gateway.api.meta.basic.Endpoint.ip', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='port', full_name='com.welab.wefe.gateway.api.meta.basic.Endpoint.port', index=1,
            number=2, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='hostname', full_name='com.welab.wefe.gateway.api.meta.basic.Endpoint.hostname', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=59,
    serialized_end=113,
)

_ENDPOINTS = _descriptor.Descriptor(
    name='Endpoints',
    full_name='com.welab.wefe.gateway.api.meta.basic.Endpoints',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='endpoints', full_name='com.welab.wefe.gateway.api.meta.basic.Endpoints.endpoints', index=0,
            number=1, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=115,
    serialized_end=194,
)

_RETURNSTATUS = _descriptor.Descriptor(
    name='ReturnStatus',
    full_name='com.welab.wefe.gateway.api.meta.basic.ReturnStatus',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='code', full_name='com.welab.wefe.gateway.api.meta.basic.ReturnStatus.code', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='message', full_name='com.welab.wefe.gateway.api.meta.basic.ReturnStatus.message', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='sessionId', full_name='com.welab.wefe.gateway.api.meta.basic.ReturnStatus.sessionId', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='data', full_name='com.welab.wefe.gateway.api.meta.basic.ReturnStatus.data', index=3,
            number=4, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=196,
    serialized_end=274,
)

_ENDPOINTS.fields_by_name['endpoints'].message_type = _ENDPOINT
DESCRIPTOR.message_types_by_name['Endpoint'] = _ENDPOINT
DESCRIPTOR.message_types_by_name['Endpoints'] = _ENDPOINTS
DESCRIPTOR.message_types_by_name['ReturnStatus'] = _RETURNSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Endpoint = _reflection.GeneratedProtocolMessageType('Endpoint', (_message.Message,), {
    'DESCRIPTOR': _ENDPOINT,
    '__module__': 'basic_meta_pb2'
    # @@protoc_insertion_point(class_scope:com.welab.wefe.gateway.api.meta.basic.Endpoint)
})
_sym_db.RegisterMessage(Endpoint)

Endpoints = _reflection.GeneratedProtocolMessageType('Endpoints', (_message.Message,), {
    'DESCRIPTOR': _ENDPOINTS,
    '__module__': 'basic_meta_pb2'
    # @@protoc_insertion_point(class_scope:com.welab.wefe.gateway.api.meta.basic.Endpoints)
})
_sym_db.RegisterMessage(Endpoints)

ReturnStatus = _reflection.GeneratedProtocolMessageType('ReturnStatus', (_message.Message,), {
    'DESCRIPTOR': _RETURNSTATUS,
    '__module__': 'basic_meta_pb2'
    # @@protoc_insertion_point(class_scope:com.welab.wefe.gateway.api.meta.basic.ReturnStatus)
})
_sym_db.RegisterMessage(ReturnStatus)

DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
