# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway-service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

import basic_meta_pb2 as basic__meta__pb2
import gateway_meta_pb2 as gateway__meta__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name='gateway-service.proto',
    package='com.welab.wefe.gateway.api.service.proto',
    syntax='proto3',
    serialized_options=b'B\024TransferServiceProto',
    serialized_pb=b'\n\x15gateway-service.proto\x12(com.welab.wefe.gateway.api.service.proto\x1a\x10\x62\x61sic-meta.proto\x1a\x12gateway-meta.proto2\xf1\x02\n\x0fTransferService\x12p\n\x04send\x12\x33.com.welab.wefe.gateway.api.meta.basic.TransferMeta\x1a\x33.com.welab.wefe.gateway.api.meta.basic.ReturnStatus\x12p\n\x04recv\x12\x33.com.welab.wefe.gateway.api.meta.basic.TransferMeta\x1a\x33.com.welab.wefe.gateway.api.meta.basic.TransferMeta\x12z\n\x0e\x63heckStatusNow\x12\x33.com.welab.wefe.gateway.api.meta.basic.TransferMeta\x1a\x33.com.welab.wefe.gateway.api.meta.basic.TransferMeta2\x8d\x02\n\x1fNetworkDataTransferProxyService\x12p\n\x04push\x12\x33.com.welab.wefe.gateway.api.meta.basic.TransferMeta\x1a\x33.com.welab.wefe.gateway.api.meta.basic.ReturnStatus\x12x\n\x08pushData\x12\x33.com.welab.wefe.gateway.api.meta.basic.TransferMeta\x1a\x33.com.welab.wefe.gateway.api.meta.basic.ReturnStatus(\x01\x30\x01\x42\x16\x42\x14TransferServiceProtob\x06proto3'
    ,
    dependencies=[basic__meta__pb2.DESCRIPTOR, gateway__meta__pb2.DESCRIPTOR, ])

_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DESCRIPTOR._options = None

_TRANSFERSERVICE = _descriptor.ServiceDescriptor(
    name='TransferService',
    full_name='com.welab.wefe.gateway.api.service.proto.TransferService',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=106,
    serialized_end=475,
    methods=[
        _descriptor.MethodDescriptor(
            name='send',
            full_name='com.welab.wefe.gateway.api.service.proto.TransferService.send',
            index=0,
            containing_service=None,
            input_type=gateway__meta__pb2._TRANSFERMETA,
            output_type=basic__meta__pb2._RETURNSTATUS,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name='recv',
            full_name='com.welab.wefe.gateway.api.service.proto.TransferService.recv',
            index=1,
            containing_service=None,
            input_type=gateway__meta__pb2._TRANSFERMETA,
            output_type=gateway__meta__pb2._TRANSFERMETA,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name='checkStatusNow',
            full_name='com.welab.wefe.gateway.api.service.proto.TransferService.checkStatusNow',
            index=2,
            containing_service=None,
            input_type=gateway__meta__pb2._TRANSFERMETA,
            output_type=gateway__meta__pb2._TRANSFERMETA,
            serialized_options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_TRANSFERSERVICE)

DESCRIPTOR.services_by_name['TransferService'] = _TRANSFERSERVICE

_NETWORKDATATRANSFERPROXYSERVICE = _descriptor.ServiceDescriptor(
    name='NetworkDataTransferProxyService',
    full_name='com.welab.wefe.gateway.api.service.proto.NetworkDataTransferProxyService',
    file=DESCRIPTOR,
    index=1,
    serialized_options=None,
    serialized_start=478,
    serialized_end=747,
    methods=[
        _descriptor.MethodDescriptor(
            name='push',
            full_name='com.welab.wefe.gateway.api.service.proto.NetworkDataTransferProxyService.push',
            index=0,
            containing_service=None,
            input_type=gateway__meta__pb2._TRANSFERMETA,
            output_type=basic__meta__pb2._RETURNSTATUS,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name='pushData',
            full_name='com.welab.wefe.gateway.api.service.proto.NetworkDataTransferProxyService.pushData',
            index=1,
            containing_service=None,
            input_type=gateway__meta__pb2._TRANSFERMETA,
            output_type=basic__meta__pb2._RETURNSTATUS,
            serialized_options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_NETWORKDATATRANSFERPROXYSERVICE)

DESCRIPTOR.services_by_name['NetworkDataTransferProxyService'] = _NETWORKDATATRANSFERPROXYSERVICE

# @@protoc_insertion_point(module_scope)
