# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway-meta.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import basic_meta_pb2 as basic__meta__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gateway-meta.proto',
  package='com.welab.wefe.gateway.api.meta.basic',
  syntax='proto3',
  serialized_options=b'B\020GatewayMetaProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12gateway-meta.proto\x12%com.welab.wefe.gateway.api.meta.basic\x1a\x10\x62\x61sic-meta.proto\"q\n\x06Member\x12\x10\n\x08memberId\x18\x01 \x01(\t\x12\x12\n\nmemberName\x18\x02 \x01(\t\x12\x41\n\x08\x65ndpoint\x18\x03 \x01(\x0b\x32/.com.welab.wefe.gateway.api.meta.basic.Endpoint\"x\n\x07\x43ontent\x12\x0f\n\x07strData\x18\x01 \x01(\t\x12\x10\n\x08\x62yteData\x18\x03 \x01(\x0c\x12J\n\rkeyValueDatas\x18\x02 \x03(\x0b\x32\x33.com.welab.wefe.gateway.api.meta.basic.KeyValueData\"\xcb\x03\n\x0cTransferMeta\x12:\n\x03src\x18\x01 \x01(\x0b\x32-.com.welab.wefe.gateway.api.meta.basic.Member\x12:\n\x03\x64st\x18\x02 \x01(\x0b\x32-.com.welab.wefe.gateway.api.meta.basic.Member\x12?\n\x07\x63ontent\x18\x03 \x01(\x0b\x32..com.welab.wefe.gateway.api.meta.basic.Content\x12\x11\n\tprocessor\x18\x04 \x01(\t\x12M\n\x0etransferStatus\x18\x05 \x01(\x0e\x32\x35.com.welab.wefe.gateway.api.meta.basic.TransferStatus\x12\x11\n\tsessionId\x18\x06 \x01(\t\x12\x13\n\x0breceiveDate\x18\x07 \x01(\x03\x12\x12\n\nexpireDate\x18\x08 \x01(\x03\x12\x12\n\nsequenceNo\x18\t \x01(\x05\x12\x15\n\rsequenceIsEnd\x18\n \x01(\x08\x12\x1a\n\x12taggedVariableName\x18\x0b \x01(\x0c\x12\x0b\n\x03tag\x18\x0c \x01(\t\x12\x10\n\x08\x65xtField\x18\r \x01(\t*m\n\x0eTransferStatus\x12\x11\n\rNOT_PROCESSED\x10\x00\x12\x10\n\x0cINITIALIZING\x10\x01\x12\x0e\n\nPROCESSING\x10\x02\x12\x0c\n\x08\x43OMPLETE\x10\x03\x12\t\n\x05\x45RROR\x10\x04\x12\r\n\tCANCELLED\x10\x05\x42\x12\x42\x10GatewayMetaProtob\x06proto3'
  ,
  dependencies=[basic__meta__pb2.DESCRIPTOR,])

_TRANSFERSTATUS = _descriptor.EnumDescriptor(
  name='TransferStatus',
  full_name='com.welab.wefe.gateway.api.meta.basic.TransferStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOT_PROCESSED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INITIALIZING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROCESSING', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='COMPLETE', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CANCELLED', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=778,
  serialized_end=887,
)
_sym_db.RegisterEnumDescriptor(_TRANSFERSTATUS)

TransferStatus = enum_type_wrapper.EnumTypeWrapper(_TRANSFERSTATUS)
NOT_PROCESSED = 0
INITIALIZING = 1
PROCESSING = 2
COMPLETE = 3
ERROR = 4
CANCELLED = 5



_MEMBER = _descriptor.Descriptor(
  name='Member',
  full_name='com.welab.wefe.gateway.api.meta.basic.Member',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='memberId', full_name='com.welab.wefe.gateway.api.meta.basic.Member.memberId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='memberName', full_name='com.welab.wefe.gateway.api.meta.basic.Member.memberName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='endpoint', full_name='com.welab.wefe.gateway.api.meta.basic.Member.endpoint', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=192,
)


_CONTENT = _descriptor.Descriptor(
  name='Content',
  full_name='com.welab.wefe.gateway.api.meta.basic.Content',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='strData', full_name='com.welab.wefe.gateway.api.meta.basic.Content.strData', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='byteData', full_name='com.welab.wefe.gateway.api.meta.basic.Content.byteData', index=1,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='keyValueDatas', full_name='com.welab.wefe.gateway.api.meta.basic.Content.keyValueDatas', index=2,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=314,
)


_TRANSFERMETA = _descriptor.Descriptor(
  name='TransferMeta',
  full_name='com.welab.wefe.gateway.api.meta.basic.TransferMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='src', full_name='com.welab.wefe.gateway.api.meta.basic.TransferMeta.src', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dst', full_name='com.welab.wefe.gateway.api.meta.basic.TransferMeta.dst', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='com.welab.wefe.gateway.api.meta.basic.TransferMeta.content', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='processor', full_name='com.welab.wefe.gateway.api.meta.basic.TransferMeta.processor', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transferStatus', full_name='com.welab.wefe.gateway.api.meta.basic.TransferMeta.transferStatus', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sessionId', full_name='com.welab.wefe.gateway.api.meta.basic.TransferMeta.sessionId', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='receiveDate', full_name='com.welab.wefe.gateway.api.meta.basic.TransferMeta.receiveDate', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='expireDate', full_name='com.welab.wefe.gateway.api.meta.basic.TransferMeta.expireDate', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sequenceNo', full_name='com.welab.wefe.gateway.api.meta.basic.TransferMeta.sequenceNo', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sequenceIsEnd', full_name='com.welab.wefe.gateway.api.meta.basic.TransferMeta.sequenceIsEnd', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='taggedVariableName', full_name='com.welab.wefe.gateway.api.meta.basic.TransferMeta.taggedVariableName', index=10,
      number=11, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tag', full_name='com.welab.wefe.gateway.api.meta.basic.TransferMeta.tag', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extField', full_name='com.welab.wefe.gateway.api.meta.basic.TransferMeta.extField', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=776,
)

_MEMBER.fields_by_name['endpoint'].message_type = basic__meta__pb2._ENDPOINT
_CONTENT.fields_by_name['keyValueDatas'].message_type = basic__meta__pb2._KEYVALUEDATA
_TRANSFERMETA.fields_by_name['src'].message_type = _MEMBER
_TRANSFERMETA.fields_by_name['dst'].message_type = _MEMBER
_TRANSFERMETA.fields_by_name['content'].message_type = _CONTENT
_TRANSFERMETA.fields_by_name['transferStatus'].enum_type = _TRANSFERSTATUS
DESCRIPTOR.message_types_by_name['Member'] = _MEMBER
DESCRIPTOR.message_types_by_name['Content'] = _CONTENT
DESCRIPTOR.message_types_by_name['TransferMeta'] = _TRANSFERMETA
DESCRIPTOR.enum_types_by_name['TransferStatus'] = _TRANSFERSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Member = _reflection.GeneratedProtocolMessageType('Member', (_message.Message,), {
  'DESCRIPTOR' : _MEMBER,
  '__module__' : 'gateway_meta_pb2'
  # @@protoc_insertion_point(class_scope:com.welab.wefe.gateway.api.meta.basic.Member)
  })
_sym_db.RegisterMessage(Member)

Content = _reflection.GeneratedProtocolMessageType('Content', (_message.Message,), {
  'DESCRIPTOR' : _CONTENT,
  '__module__' : 'gateway_meta_pb2'
  # @@protoc_insertion_point(class_scope:com.welab.wefe.gateway.api.meta.basic.Content)
  })
_sym_db.RegisterMessage(Content)

TransferMeta = _reflection.GeneratedProtocolMessageType('TransferMeta', (_message.Message,), {
  'DESCRIPTOR' : _TRANSFERMETA,
  '__module__' : 'gateway_meta_pb2'
  # @@protoc_insertion_point(class_scope:com.welab.wefe.gateway.api.meta.basic.TransferMeta)
  })
_sym_db.RegisterMessage(TransferMeta)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
