# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: intermediate-data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='intermediate-data.proto',
    package='com.welab.wefe.gateway.api.meta.storage',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=b'\n\x17intermediate-data.proto\x12\'com.welab.wefe.gateway.api.meta.storage\"2\n\x14IntermediateDataItem\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\r\n\x05value\x18\x02 \x01(\x0c\"k\n\x10IntermediateData\x12W\n\x10intermediateData\x18\x01 \x03(\x0b\x32=.com.welab.wefe.gateway.api.meta.storage.IntermediateDataItemb\x06proto3'
)

_INTERMEDIATEDATAITEM = _descriptor.Descriptor(
    name='IntermediateDataItem',
    full_name='com.welab.wefe.gateway.api.meta.storage.IntermediateDataItem',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='key', full_name='com.welab.wefe.gateway.api.meta.storage.IntermediateDataItem.key', index=0,
            number=1, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value=b"",
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='value', full_name='com.welab.wefe.gateway.api.meta.storage.IntermediateDataItem.value', index=1,
            number=2, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value=b"",
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=68,
    serialized_end=118,
)

_INTERMEDIATEDATA = _descriptor.Descriptor(
    name='IntermediateData',
    full_name='com.welab.wefe.gateway.api.meta.storage.IntermediateData',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='intermediateData',
            full_name='com.welab.wefe.gateway.api.meta.storage.IntermediateData.intermediateData', index=0,
            number=1, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=120,
    serialized_end=227,
)

_INTERMEDIATEDATA.fields_by_name['intermediateData'].message_type = _INTERMEDIATEDATAITEM
DESCRIPTOR.message_types_by_name['IntermediateDataItem'] = _INTERMEDIATEDATAITEM
DESCRIPTOR.message_types_by_name['IntermediateData'] = _INTERMEDIATEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IntermediateDataItem = _reflection.GeneratedProtocolMessageType('IntermediateDataItem', (_message.Message,), {
    'DESCRIPTOR': _INTERMEDIATEDATAITEM,
    '__module__': 'intermediate_data_pb2'
    # @@protoc_insertion_point(class_scope:com.welab.wefe.gateway.api.meta.storage.IntermediateDataItem)
})
_sym_db.RegisterMessage(IntermediateDataItem)

IntermediateData = _reflection.GeneratedProtocolMessageType('IntermediateData', (_message.Message,), {
    'DESCRIPTOR': _INTERMEDIATEDATA,
    '__module__': 'intermediate_data_pb2'
    # @@protoc_insertion_point(class_scope:com.welab.wefe.gateway.api.meta.storage.IntermediateData)
})
_sym_db.RegisterMessage(IntermediateData)

# @@protoc_insertion_point(module_scope)
