# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: storage-basic.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import enum_type_wrapper

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='storage-basic.proto',
    package='com.welab.wefe.gateway.api.meta.storage',
    syntax='proto3',
    serialized_options=b'B\020StorageMetaProto',
    serialized_pb=b'\n\x13storage-basic.proto\x12\'com.welab.wefe.gateway.api.meta.storage\"\x87\x01\n\x0eStorageLocator\x12\x42\n\x04type\x18\x01 \x01(\x0e\x32\x34.com.welab.wefe.gateway.api.meta.storage.StorageType\x12\x11\n\tnamespace\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x10\n\x08\x66ragment\x18\x04 \x01(\x05*(\n\x0bStorageType\x12\x08\n\x04LMDB\x10\x00\x12\x0f\n\x0b\x43LICK_HOUSE\x10\x01\x42\x12\x42\x10StorageMetaProtob\x06proto3'
)

_STORAGETYPE = _descriptor.EnumDescriptor(
    name='StorageType',
    full_name='com.welab.wefe.gateway.api.meta.storage.StorageType',
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name='LMDB', index=0, number=0,
            serialized_options=None,
            type=None),
        _descriptor.EnumValueDescriptor(
            name='CLICK_HOUSE', index=1, number=1,
            serialized_options=None,
            type=None),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=202,
    serialized_end=242,
)
_sym_db.RegisterEnumDescriptor(_STORAGETYPE)

StorageType = enum_type_wrapper.EnumTypeWrapper(_STORAGETYPE)
LMDB = 0
CLICK_HOUSE = 1

_STORAGELOCATOR = _descriptor.Descriptor(
    name='StorageLocator',
    full_name='com.welab.wefe.gateway.api.meta.storage.StorageLocator',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='type', full_name='com.welab.wefe.gateway.api.meta.storage.StorageLocator.type', index=0,
            number=1, type=14, cpp_type=8, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='namespace', full_name='com.welab.wefe.gateway.api.meta.storage.StorageLocator.namespace', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='name', full_name='com.welab.wefe.gateway.api.meta.storage.StorageLocator.name', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='fragment', full_name='com.welab.wefe.gateway.api.meta.storage.StorageLocator.fragment', index=3,
            number=4, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=65,
    serialized_end=200,
)

_STORAGELOCATOR.fields_by_name['type'].enum_type = _STORAGETYPE
DESCRIPTOR.message_types_by_name['StorageLocator'] = _STORAGELOCATOR
DESCRIPTOR.enum_types_by_name['StorageType'] = _STORAGETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StorageLocator = _reflection.GeneratedProtocolMessageType('StorageLocator', (_message.Message,), {
    'DESCRIPTOR': _STORAGELOCATOR,
    '__module__': 'storage_basic_pb2'
    # @@protoc_insertion_point(class_scope:com.welab.wefe.gateway.api.meta.storage.StorageLocator)
})
_sym_db.RegisterMessage(StorageLocator)

DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
