version: "3"
services:

  wefe_fusion_website:
    image: wefe_fusion_website:v.2.1 # wefe_version
    ports:
      - 80:80 # website_port
    restart: always
    privileged: true
    networks:
      - network
    volumes:
      - "./mount/default.conf:/etc/nginx/conf.d/default.conf"
      - "./mount/fusion-website:/opt/website/fusion-website"

networks:
  network:
    driver: bridge