
### 查询全部 tag
POST http://localhost:8080/board-service/union/tag/query
Content-Type: application/json

{}

> {%

client.test("Request executed successfully", function() {
    client.assert(response.body.code === 0, "Response code is not 0");
});

%}



### 按名字查
POST http://localhost:8080/board-service/union/tag/query
Content-Type: application/json

{
  "tag": "xlsx"
}
