version: "3"
services:

  wefe_manager_service:
    image: wefe_manager_service:v.2.1 # wefe_version
    ports:
      - 8800:8080 # service_port
    restart: always
    privileged: true
    networks:
      - network
    volumes:
      - "/data/wefe/docker-compose/logs/wefe-manager-service:/data/logs/wefe-manager-service" # service_logs
      - "./mount/start.sh:/opt/service/start.sh"
      - "./mount/application.properties:/opt/service/application.properties"
      - "./mount/manager-service.jar:/opt/service/manager-service.jar"
      - "./mount/cert:/opt/service/cert"

networks:
  network:
    driver: bridge