// icons
import * as elIcons from '@element-plus/icons';

// components
import {
    ElAutocomplete,
    ElDescriptions,
    ElRow,
    ElCol,
    ElContainer,
    ElIcon,
    ElButton,
    ElLink,
    ElRadio,
    ElCheckbox,
    ElInput,
    ElInputNumber,
    ElProgress,
    ElSelect,
    ElSwitch,
    ElTimePicker,
    ElDatePicker,
    ElUpload,
    ElForm,
    ElTag,
    ElTree,
    ElPagination,
    ElBadge,
    ElAlert,
    ElMessage,
    ElLoading,
    ElMenu,
    ElTabs,
    ElBreadcrumb,
    ElSlider,
    ElSteps,
    ElPopover,
    ElDropdown,
    ElDialog,
    ElMessageBox,
    ElNotification,
    ElTooltip,
    ElCard,
    ElCarousel,
    ElCollapse,
    ElDivider,
    ElImage,
    ElInfiniteScroll,
    ElDrawer,
    ElScrollbar,
    ElTable,
} from 'element-plus';

const elComponents = {
    ElAutocomplete,
    ElDescriptions,
    ElRow,
    ElCol,
    ElContainer,
    ElIcon,
    ElButton,
    ElLink,
    ElRadio,
    ElCheckbox,
    ElInput,
    ElInputNumber,
    ElProgress,
    ElSelect,
    ElSwitch,
    ElTimePicker,
    ElDatePicker,
    ElUpload,
    ElForm,
    ElTag,
    ElTree,
    ElPagination,
    ElBadge,
    ElAlert,
    ElMessage,
    ElLoading,
    ElMenu,
    ElTabs,
    ElBreadcrumb,
    ElSlider,
    ElDropdown,
    ElSteps,
    ElDialog,
    ElMessageBox,
    ElNotification,
    ElTooltip,
    ElPopover,
    ElCard,
    ElCarousel,
    ElCollapse,
    ElDivider,
    ElImage,
    ElInfiniteScroll,
    ElDrawer,
    ElScrollbar,
    ElTable,
};

export { elIcons, elComponents };
