
### 添加图片数据集-目标检测
POST localhost:8080/board-service/image_data_set/add
Content-Type: application/json
token: {{token}}

{
  "publicLevel": "Public",
  "name": "zane test10",
  "tags": [
    "12321"
  ],
  "description": "",
  "public_member_list": "",
  "filename": "fl_fruit_yippee.zip",
  "for_job_type": "detection"
}


### 添加图片数据集-图像分类
POST localhost:8080/board-service/image_data_set/add
Content-Type: application/json
token: {{token}}

{
  "publicLevel": "Public",
  "name": "zane test12",
  "tags": [
    "12321"
  ],
  "description": "",
  "public_member_list": "",
  "filename": "flowers.zip",
  "for_job_type": "classify"
}

