###
POST http://localhost:8080/board-service/project/add
Content-Type: application/json
token: {{token}}

{
  "name": "添加datatype",
  "desc": "bug重现",
  "projectType": "MachineLearning",
  "promoterDataSetList": [
    {
      "member_role": "promoter",
      "member_id": "290007c2a71d470ba00f486b18875d31",
      "data_set_id": "8a675a8f7a2e48f6bcbaece3cdfca3d6",
      "data_set_type": "TableDataSet"
    }
  ],
  "providerList": [
    {
      "member_id": "d0f47307804844898ecfc65b875abe87",
      "dataSetList": [
        {
          "member_role": "provider",
          "member_id": "d0f47307804844898ecfc65b875abe87",
          "data_set_id": "c81ad8dbe793410db43594bfc36afb11",
          "data_set_type": "TableDataSet"
        }
      ]
    },
    {
      "member_id": "8896e74890a5459386287ec817e8b4f3",
      "dataSetList": [
        {
          "member_role": "provider",
          "member_id": "8896e74890a5459386287ec817e8b4f3",
          "data_set_id": "eea81ef35a9e45bbb18cad5c251b8280",
          "data_set_type": "TableDataSet"
        },
        {
          "member_role": "provider",
          "member_id": "8896e74890a5459386287ec817e8b4f3",
          "data_set_id": "8c7e7065785844fcaf2cbcda4d44fba8",
          "data_set_type": "TableDataSet"
        }
      ]
    }
  ],
  "promoterList": []
}