POST http://localhost:8080/board-service/project/flow/node/update
Content-Type: application/json
token: {{token}}

{
  "nodeId": "16196070742596633",
  "componentType": "DataIO",
  "flowId": "27f72edb3e7e4ac698dea3fe238b735d",
  "params": {
    "dataset_list": [
      {
        "member_id": "81051c7b7f4f4beaa581ba046f8a6048",
        "member_role": "promoter",
        "data_set_id": "88047fb892a44e3d8496e4c21a1f9432",
        "features": [
          "x1",
          "x2",
          "x3",
          "x4",
          "x5",
          "x6",
          "x7",
          "x8",
          "x9",
          "x10",
          "x11",
          "x12",
          "x13",
          "x14",
          "x15",
          "x16",
          "x17",
          "x18",
          "x19",
          "x20"
        ],
        "feature_name_list": "x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19,x20",
        "feature_count": 20,
        "contains_y": true,
        "derived_from": null,
        "row_count": 500,
        "name": "500-y03"
      },
      {
        "member_id": "a94d7a71189c44b5a298ad4ed2668f67",
        "member_role": "provider",
        "data_set_id": "f884fe77643a4d5995c0f29eed71ff9a",
        "features": [
          "x1",
          "x2",
          "x3",
          "x4",
          "x5",
          "x6",
          "x7",
          "x8",
          "x9",
          "x10",
          "x11",
          "x12",
          "x13",
          "x14",
          "x15",
          "x16",
          "x17",
          "x18",
          "x19",
          "x20"
        ],
        "feature_name_list": "x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19,x20",
        "feature_count": 20,
        "contains_y": false,
        "derived_from": null,
        "row_count": 500,
        "name": "500-无-y"
      }
    ]
  }
}



### 自动创建

GET http://localhost:8080/board-service/project/flow/node/update?nodeId=16088878120465932&componentType=FeatureStatistic&flow_id=a9632fcc436f4400bba1726532475f7b


### debug

POST http://localhost:8080/board-service/project/flow/node/update
Content-Type: application/json


{
  "nodeId": "16088893089992860",
  "componentType": "FeatureStatistic",
  "flow_id": "a9632fcc436f4400bba1726532475f7b",
  "params": {
    "featureMethods": [
      {
        "name": "Max",
        "value": ""
      },
      {
        "name": "Min",
        "value": ""
      },
      {
        "name": "Percentile",
        "value": 50
      }
    ],
    "members": [
      {
        "memberId": "682d087e965a4c5d8a2807a772a571c1",
        "features": [
          "x4",
          "x5",
          "x6",
          "x7"
        ]
      },
      {
        "memberId": "269330b21e1342b48124303e55c75ce0",
        "features": [
          "id",
          "y",
          "x1"
        ]
      }
    ]
  }
}