POST http://localhost:8080/board-service/project/modeling/query
Content-Type: application/json

{
  "projectId": "ac6c60a15875487f8b32864512920653",
  "componentType": "HorzLR"
}

###
GET http://localhost:8080/board-service/project/modeling/query?name=&flow_id=&component_type=&project_id=58104fea3f2c4b0e8e07d30d560bbbca&job_id=&project_type=MachineLearning&page_index=0&page_size=10
Content-Type: application/json
token: {{token}}

