data_promoter: "data/breast_horz_promoter.csv"
data_provider: "data/breast_horz_provider.csv"
promoter_data_table: "breast_horz_promoter"
provider_data_table: "breast_horz_provider"
epoch: 150
lr: 0.05
batch_size: 32
optimizer: Adam
encode_label: true
layers:
  - class_name: Dense
    config: { units: 5, input_shape: [ 18 ], activation: relu }
  - class_name: Dense
    config: { units: 4, activation: softmax }
dataset: vehicle
loss: categorical_crossentropy
is_multy: true
metrics: [ "accuracy" ]