data_promoter: "data/breast_horz_promoter.csv"
data_provider: "data/breast_horz_provider.csv"
promoter_data_table: "breast_horz_promoter"
provider_data_table: "breast_horz_provider"
epoch: 100
lr: 0.05
batch_size: 32
optimizer: Adam
encode_label: false
layers:
  - name: Dense
    params: { units: 1, input_shape: [ 30, ], activation: sigmoid }
dataset: breast
loss: binary_crossentropy
is_multy: false
metrics: [ "accuracy" ]