POST http://localhost:8080/board-service/project/member/add
Content-Type: application/json

{
  "project_id": "3a53a880343a4720829b9deaf4aca160",
  "memberList": [
    {
      "member_id": "682d087e965a4c5d8a2807a772a571c1",
      "member_name": "弟依偎零四",
      "member_role": "provider"
    }
  ]
}