GET http://localhost:8080/board-service/project/job/finished?job_id=835f32491c994a6d9d8e9759fe60e0c2&sign=tm2ckFD/9aO0HDtykt1K0raQ8YU0qEq9YHDbH7BndtgwpMiJwLNBUZc+rImEjKiXHKd5lSFH4KAh3eNuL841AZB4uxEVTb7RqZl0Gcp3mKrnFeJJp1QPmEGIh4TZ2e4QBybM0Fmu5ShNSBYh1lNRbq3I3Di42sxLwdwyod93e8ItEVy2XfDX+hHiJCHrqkAQGP6OXxahq8WnQUs3zlftU3DVKXGgValhKNB93CIRVa9bgocQ4dkjGcPu2RX3qGpuZ1NeDXbFYeM4Bz6O91JZUyB+ZALqpA3iU2oZk5RTV8N+jmgg2DRZg9E09CCYUIggcKyo98mdG9SZ6tjwnGkxA==