POST http://localhost:8080/board-service/flow/job/query
Content-Type: application/json
token:{{token}}

{
  "flow_id": "36ab34740ace48558f887e5ff77f99c1",
  "project_id": "6f4caef3760a4a3da785f4f46bdd41d7"
}


###

POST http://localhost:8080/board-service/flow/job/query
Content-Type: application/json

{
  "flow_id": "6b25864fa5c84be0af83ddf4a12e78bb",
  "name": "凯子"
}

###

POST http://localhost:8080/board-service/flow/job/query
Content-Type: application/json

{
  "flow_id": "6b25864fa5c84be0af83ddf4a12e78bb",
  "status": "success"
}
