### 查全部
POST http://localhost:8080/board-service/component/list
Content-Type: application/json

{}

### 查横向
POST http://localhost:8080/board-service/component/list
Content-Type: application/json

{
  "federatedLearningType": "horizontal"
}


### 查纵向
POST http://localhost:8080/board-service/component/list
Content-Type: application/json

{
  "federatedLearningType": "vertical"
}