POST http://localhost:8080/board-service/gateway/redirect
Content-Type: application/json

{
  "caller_member_role": "provider",
  "data": {
    "method": "POST",
    "project_id": "32065c74a125478581b9cd8fa980055a",
    "data_set_id": "f2088c1f8cf04530872b5490b65064e5",
    "status": "agree"
  },
  "caller_member_name": "弟依偎零四",
  "api": "project/data_set/audit",
  "caller_member_id": "682d087e965a4c5d8a2807a772a571c1"
}

###
POST http://localhost:8080/board-service/gateway/redirect
Content-Type: application/json

{
  "data": "{\"caller_member_role\":\"\",\"data\":{\"member_id\":\"727c393686b74eb680a0ed8ba539f58a\"},\"caller_member_name\":\"天冕科技01\",\"api\":\"member/available\",\"caller_member_id\":\"087973c99d26410683944bf3f46c8635\"}",
  "member_id": "727c393686b74eb680a0ed8ba539f58a",
  "sign": "FjSJhbo89zqYzWI/BCRrun8YB6FfhFDyiWGvJRMM0/EAJ0Ye19Zh7CZLjV3Qgno30zpVNT2n9SOs91uDAvJfWy1+qH/92Qk5SWYdQXzmTkAZFRq8/D5GUxFRp4syc+txe79Gg0/4kA327qEcN6pT2q+yX759S/ziTCDUHv2t1PDJaDKDUJAdwr+Pa7L21E9E6NLM4BMzUGcnJvEH3I7Z44qkFHAfTolaOHijbYi9Wxz7khMid7lYYFqtc4CWJpPJOk4ty9hImCQstUD8gU4JEdYLtOklBRKKFA/un0A2HNZg2o0VrwPbr5WzpAjDAIm5DEyI3/ORo2F+dMUOhIJ08Q=="
}