
### 登录
POST http://localhost:8080/board-service/account/login
Content-Type: application/json

{
  "phone_number": "13100000001",
  "password": "password",
  "code": "code",
  "key": "key"
}

> {%
client.global.set("token", response.body.data.token);
%}

