
### 更新 member 信息
POST http://localhost:8080/board-service/member/update
Content-Type: application/json
token: {{token}}

{
  "memberName": "星环科技",
  "memberEmail": "galaxy@galaxy.com",
  "memberMobile": "400-88888888",
  "memberAllowPublicDataSet": true
}

> {%

client.global.set("token", response.body.data.token);

client.test("Request executed successfully", function() {
    client.assert(response.body.code === 0, "Response code is not 0");
});

%}

