POST http://localhost:8080/board-service/flow/job/task/feature
Content-Type: application/json
token:{{token}}


{
  "job_id": "c83f128270184311abf70c0c1b64b276",
  "flow_id": "cf6008d8c91e498ba415c099baed3019",
  "flow_node_id": "16663216807991414"
}

###
