version: "3"
services:

  wefe_serving_service:
    image: wefe_serving_service:v.2.1 # wefe_version
    ports:
      - 8800:8080 # service_port
    restart: always
    privileged: true
    networks:
      - network
    volumes:
      - "/data/wefe/docker-compose/logs/wefe-serving-service:/data/logs/wefe-serving-service" # service_logs
      - "./mount/start.sh:/opt/service/start.sh"
      - "./mount/config.properties:/opt/service/config.properties"
      - "./mount/application.properties:/opt/service/application.properties"
      - "./mount/serving-service.jar:/opt/service/serving-service.jar"

networks:
  network:
    driver: bridge