
### 查询全部消息
POST http://localhost:8080/board-service/message/query
Content-Type: application/json

{}


### 查未读消息
POST http://localhost:8080/board-service/message/query
Content-Type: application/json

{
  "unread": true
}


### 按 level 查
POST http://localhost:8080/board-service/message/query
Content-Type: application/json

{
  "level": "error"
}
