
### 查询全部消息
POST {{baseUrl}}/message/query
Content-Type: application/json

{}


### 查未读消息
POST {{baseUrl}}/message/query
Content-Type: application/json

{
  "unread": true
}


### 按 level 查
POST {{baseUrl}}/message/query
Content-Type: application/json

{
  "level": "error"
}
